# Tensorflow

In [1]:
import tensorflow as tf

In [3]:
# Stałe
a = tf.constant([2])
b = tf.constant([3])

c = tf.add(a, b)

In [4]:
# Żeby wykonać jakąkolwiek operację, należy zainicjalizować sesję
session = tf.Session()

In [5]:
result = session.run(c)
print result

[5]


In [6]:
# Zwolnienie zasobów następuje poprzeze zamknięcie sesji
session.close()

In [7]:
# Aby automatycznie zamknąć sesję po wykonaniu wszystkich operacji,
# możemy użyć bloku with
with tf.Session() as session:
    result = session.run(c)
    print result

[5]


In [9]:
# Różne wymiary 
scalar = tf.constant([2])
vector = tf.constant([5, 6, 2])
matrix = tf.constant([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
tensor = tf.constant([ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ])

with tf.Session() as session:
    print session.run(scalar)
    print session.run(vector)
    print session.run(matrix)
    print session.run(tensor)


[2]
[5 6 2]
[[1 2 3]
 [2 3 4]
 [3 4 5]]
[[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]]


In [10]:
# Mnożenie macierzy

matrix_one = tf.constant([[2,3],[3,4]])
matrix_second = tf.constant([[2,3],[3,4]])

first_operation = tf.matmul(matrix_one, matrix_second)

with tf.Session() as session:
    print session.run(first_operation)

[[13 18]
 [18 25]]


In [12]:
# Zmienne
state = tf.Variable(0)
one = tf.constant(1)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)

# Zmienne muszą zostać zainicjalizowane
init_op = tf.global_variables_initializer()

# Jeśli operacje pociągają za sobą inne, nie muszą być
# explicite wywoływane w sesji np.
# wywołujemy update, ale nie muaimy sami uruchamiać 
# new_value

with tf.Session() as session:
    session.run(init_op)
    print session.run(state)
    for _ in range(3):
        session.run(update)
        print session.run(state)
    

0
1
2
3


In [14]:
# Jeśli chcemy użyć w modelu danych z zewnątrz, nieznanych 
# w momencie jego tworzenia, musimy użyć placeholderów

# Tworzymy placeholder i określamy jego typ
a = tf.placeholder(tf.float32)

b = a * 2

# Przy uruchamianiu sesji, musimy nakarmić nasz model 
# potrzebnymi mu danymi

dictionary={a: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }


with tf.Session() as session:
    #result = session.run(b, feed_dict={a: 3.5})
    result = session.run(b, feed_dict=dictionary)
    print result


[[[  2.   4.   6.]
  [  8.  10.  12.]
  [ 14.  16.  18.]
  [ 20.  22.  24.]]

 [[ 26.  28.  30.]
  [ 32.  34.  36.]
  [ 38.  40.  42.]
  [ 44.  46.  48.]]]


In [15]:
# Operacje

a = tf.constant([5])
b = tf.constant([2])
c = tf.add(a, b)
d = tf.sub(a, b)

with tf.Session() as session:
    print "c:", session.run(c)
    print "d:", session.run(d)

c: [7]
d: [3]
